<a href="https://colab.research.google.com/github/pratik-chakraborty10/Machine_Learning/blob/main/OHE(Nominal_Data).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('/content/cars.csv')

In [3]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [4]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [6]:
df['brand'].nunique() # total brands

32

In [7]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [8]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

# **OHE USING PANDAS**

In [9]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

# **K-1 COLUMNS**

In [11]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True) #solving multicolinearity problem by dropping 1 columns from each category

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# **OHE USING SCIKIT-LEARN**

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=42)

In [14]:
X_train.head()

        brand  km_driven    fuel                 owner
6518     Tata       2560  Petrol           First Owner
6144    Honda      80000  Petrol          Second Owner
6381  Hyundai     150000  Diesel  Fourth & Above Owner
438    Maruti     120000  Diesel          Second Owner
5939   Maruti      25000  Petrol           First Owner

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [31]:
ohe=OneHotEncoder(drop='first',sparse=False,dtype=np.int32)

In [33]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [35]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [36]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)) # merge using numpy

array([['Tata', 2560, 0, ..., 0, 0, 0],
       ['Honda', 80000, 0, ..., 1, 0, 0],
       ['Hyundai', 150000, 1, ..., 0, 0, 0],
       ...,
       ['Hyundai', 35000, 0, ..., 0, 0, 0],
       ['Maruti', 27000, 1, ..., 0, 0, 0],
       ['Maruti', 70000, 0, ..., 1, 0, 0]], dtype=object)

In [30]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)

# **OHE WITH TOP CATEGORIES**

In [37]:
counts = df['brand'].value_counts()

In [38]:
df['brand'].nunique()
threshold = 100

In [39]:
replace = counts[counts <= threshold].index

In [41]:
pd.get_dummies(df['brand'].replace(replace, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
3967,False,False,True,False,False,False,False,False,False,False,False,False,False
5082,False,False,False,False,False,True,False,False,False,False,False,False,False
3735,False,False,False,False,False,False,True,False,False,False,False,False,False
7139,False,False,False,True,False,False,False,False,False,False,False,False,False
3257,False,False,False,False,False,False,True,False,False,False,False,False,False